make run:
	python projeto2.py 1 database1.txt
	python projeto2.py 1 database1.txt
	python projeto2.py 1 database1.txt
	python projeto2.py 1 database1.txt
	python projeto2.py 1 database1.txt
	python projeto2.py 2 database1.txt
	python projeto2.py 2 database1.txt
	python projeto2.py 2 database1.txt
	python projeto2.py 2 database1.txt
	python projeto2.py 2 database1.txt
	python projeto2.py 3 database1.txt
	python projeto2.py 3 database1.txt
	python projeto2.py 3 database1.txt
	python projeto2.py 3 database1.txt
	python projeto2.py 3 database1.txt
	python projeto2.py 4 database1.txt
	python projeto2.py 4 database1.txt
	python projeto2.py 4 database1.txt
	python projeto2.py 4 database1.txt
	python projeto2.py 4 database1.txt
	python projeto2.py 1 database2.txt
	python projeto2.py 1 database2.txt
	python projeto2.py 1 database2.txt
	python projeto2.py 1 database2.txt
	python projeto2.py 1 database2.txt
	python projeto2.py 2 database2.txt
	python projeto2.py 2 database2.txt
	python projeto2.py 2 database2.txt
	python projeto2.py 2 database2.txt
	python projeto2.py 2 database2.txt
	python projeto2.py 3 database2.txt
	python projeto2.py 3 database2.txt
	python projeto2.py 3 database2.txt
	python projeto2.py 3 database2.txt
	python projeto2.py 3 database2.txt
	python projeto2.py 4 database2.txt
	python projeto2.py 4 database2.txt
	python projeto2.py 4 database2.txt
	python projeto2.py 4 database2.txt
	python projeto2.py 4 database2.txt
	python projeto2.py 1 database3.txt
	python projeto2.py 1 database3.txt
	python projeto2.py 1 database3.txt
	python projeto2.py 1 database3.txt
	python projeto2.py 1 database3.txt
	python projeto2.py 2 database3.txt
	python projeto2.py 2 database3.txt
	python projeto2.py 2 database3.txt
	python projeto2.py 2 database3.txt
	python projeto2.py 2 database3.txt
	python projeto2.py 3 database3.txt
	python projeto2.py 3 database3.txt
	python projeto2.py 3 database3.txt
	python projeto2.py 3 database3.txt
	python projeto2.py 3 database3.txt
	python projeto2.py 4 database3.txt
	python projeto2.py 4 database3.txt
	python projeto2.py 4 database3.txt
	python projeto2.py 4 database3.txt
	python projeto2.py 4 database3.txt
